version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - accumsan
  - adipiscing
  - aenean
  - aliquam
  - amet
  - arcu
  - asds
  - auctor
  - Augue
  - bibendum
  - blandit
  - brotli
  - colums
  - congue
  - consectetur
  - cursus
  - dictumst
  - egestas
  - eleifend
  - elementum
  - elementur
  - enim
  - etiam
  - facilisi
  - facilisis
  - Faucibus
  - fermentum
  - fontawesome
  - fortawesome
  - fvisible
  - Georgi
  - hendrerit
  - iconify
  - imperdiet
  - justo
  - lacus
  - Laoreet
  - lectus
  - litle
  - luctus
  - mauris
  - mollis
  - nibh
  - Nisl
  - nulla
  - nunc
  - Nunc
  - Odio
  - ohyeaa
  - orci
  - ornare
  - Pellentesque
  - Phind
  - porttitor
  - posuere
  - pretium
  - Proin
  - rhoncus
  - sagittis
  - senectus
  - Sociis
  - sollicitudin
  - Stackoverflow
  - suspendisse
  - svgr
  - tempor
  - tincidunt
  - turpis
  - ultrices
  - ultricies
  - unplugin
  - venenatis
  - vestibulum
  - volutpat
  - vulputate
  - webfonts
  - wght
  - xlarge
  - Yeaeee
ignoreWords: []
import: []
