version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - accumsan
  - adipiscing
  - aenean
  - aliquam
  - Aliquet
  - amet
  - arcu
  - asds
  - auctor
  - Augue
  - bibendum
  - blandit
  - brotli
  - cacheable
  - colums
  - congue
  - consectetur
  - consequat
  - cursus
  - designfil
  - dictumst
  - dignissim
  - Dignissim
  - duis
  - Duuuhhh
  - egestas
  - eleifend
  - elementum
  - elementur
  - Elems
  - enim
  - etiam
  - euismod
  - facilisi
  - facilisis
  - Faucibus
  - fermentum
  - fontawesome
  - fortawesome
  - fusce
  - fvisible
  - Georgi
  - gifsicle
  - Giraudel
  - hendrerit
  - iconify
  - Ikonfilen
  - ikontext
  - imperdiet
  - jridgewell
  - justo
  - lacinia
  - lacus
  - Laoreet
  - lectus
  - litle
  - lobortis
  - luctus
  - mauris
  - molestie
  - mollis
  - nibh
  - Nisl
  - nulla
  - nunc
  - Nunc
  - Odio
  - ohyeaa
  - orci
  - ornare
  - Pellentesque
  - pharetra
  - Phind
  - porttitor
  - posuere
  - pretium
  - produktionsfiler
  - Proin
  - Quis
  - repositoryn
  - rhoncus
  - sagittis
  - scelerisque
  - senectus
  - Sidspecifika
  - Sociis
  - sollicitudin
  - Stackoverflow
  - Starcraft
  - suspendisse
  - svgr
  - tempor
  - tincidunt
  - tortor
  - tristique
  - turpis
  - typsnittsfiler
  - ullamcorper
  - ultrices
  - ultricies
  - unplugin
  - utvecklingskod
  - Vehicula
  - velit
  - venenatis
  - versioneringssystemet
  - vestibulum
  - viverra
  - Viverra
  - volutpat
  - vulputate
  - webfonts
  - wght
  - workern
  - xlarge
  - Yeaeee
ignoreWords: []
import: []
