version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - brotli
  - colums
  - fontawesome
  - fortawesome
  - Georgi
  - iconify
  - litle
  - ohyeaa
  - Phind
  - svgr
  - unplugin
  - webfonts
  - wght
  - xlarge
  - Yeaeee
ignoreWords: []
import: []
